on:
  push:
    branches: [ master ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d")"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{ steps.date.outputs.today }}
          body: |
            ## Daily TODO

            - [ ] Randomly generated task 1
            - [ ] Randomly generated task 2
            - [ ] Randomly generated task 3

          labels: |
            daily
            todo
          assignees: ${{ secrets.EMAIL }}
          as_user: true
