# Create PAT and Email Secret

name: Create an issue on commit

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure git user email and name
        run: |
           git config --local user.email "${{ secrets.EMAIL }}"
           git config --local user.name "${{ secrets.GITHUB_ACTOR }}"     
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.pat_token }}
          title: Daily Checkin
          body: Have we completed everything we wished to today?
          name: ${{ secrets.NAME }}
          email: ${{ secrets.EMAIL }}
          as: user
