name: Create Issue on Commit

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create issue
      run: |
        title="Follow-up on task #$GITHUB_SHA"
        body="Please follow-up on task #$GITHUB_SHA and provide an update on its progress."
        labels="Follow-up, task"
        data="{\"title\":\"$title\",\"body\":\"$body\",\"labels\":[\"$labels\"]}"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d "$data" https://api.github.com/repos/${{ github.repository }}/issues
