name: Create an issue on commit

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get random title
        id: title
        run: |
          echo "::set-output name=random_title::$(shuf -n 1 /usr/share/dict/words)"
      
      - name: Get random body
        id: body
        run: |
          echo "::set-output name=random_body::$(shuf -n 10 /usr/share/dict/words | tr '\n' ' ')"
      
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: muhahaha
          body: muahhaha
