name: Create Issues on Commit

on:
  push:
    branches:
      - main

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issues
      uses: einaregilsson/create-issues-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Follow-up on task #{{ env.GITHUB_SHA }}"
        body: "Please follow-up on task #{{ env.GITHUB_SHA }} and provide an update on its progress."
        labels: "Follow-up, task"
